version: '3.5'
services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - mysql
    networks:
      - mysql
networks:
  mysql:
    driver: bridge
volumes:
  mysql:
